version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_URL=localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build:
      context: ./api
    environment:
      - REDIS_URL=localhost
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"