apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-replicaset
  namespace: vidal-guillot
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/vidal-guillot-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: ENV
          value: "production"
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: vidal-guillot
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
