apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-dev-replicaset
  namespace: vidal-guillot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-dev
  template:
    metadata:
      labels:
        app: redis-dev
    spec:
      containers:
      - name: redis-dev
        image: redis:latest
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-dev-service
  namespace: vidal-guillot
spec:
  selector:
    app: redis-dev
  ports:
    - port: 6379
      targetPort: 6379
