apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
  namespace: vidal-guillot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/projet_calculatrice/backend:latest
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis-service
        - name: RABBITMQ_HOST
          value: rabbitmq-service

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: vidal-guillot
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
