apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq-replicaset
  namespace: vidal-guillot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: vidal-guillot
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmqapi
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
