apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis
  namespace: vidal-guillot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: vidal-guillot
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
